server:
  port: 8080

spring:
  datasource:
    username: root
    password: <Your password of mysql>
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding-utf-8&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
